// Generated by nest-can-react. Do not edit.
// Page refs are stable ids. The RSC bundle still renders the .tsx page.

import { createPageRef } from 'nest-can-react';

/** src/notes/note.page.tsx */
export const NotePage = createPageRef("note");
/** src/notes/notes.page.tsx */
export const NotesPage = createPageRef("notes");
/** src/welcome/welcome.page.tsx */
export const WelcomePage = createPageRef("welcome");
