// Generated by nest-can-react. Do not edit.
// Page refs are stable ids. The RSC bundle still renders the .tsx page.

import { createPageRef } from 'nest-can-react';

/** src/cookies/clear-cookie.page.tsx */
export const ClearCookiePage = createPageRef("cookies/clear-cookie");
/** src/cookies/cookies.page.tsx */
export const CookiesPage = createPageRef("cookies/cookies");
/** src/notes/note.page.tsx */
export const NotePage = createPageRef("notes/note");
/** src/notes/notes.page.tsx */
export const NotesPage = createPageRef("notes/notes");
/** src/redir/perm.page.tsx */
export const PermPage = createPageRef("redir/perm");
/** src/redir/temp.page.tsx */
export const TempPage = createPageRef("redir/temp");
/** src/welcome/welcome.page.tsx */
export const WelcomePage = createPageRef("welcome/welcome");
